/**
 * @file omcar.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Wed Nov  5 00:47:46 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "omcar.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int omcar_requested_motor_power_message_pack(
    uint8_t *dst_p,
    const struct omcar_requested_motor_power_message_t *src_p,
    size_t size)
{
    uint8_t requested_motor_power;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    requested_motor_power = (uint8_t)src_p->requested_motor_power;
    dst_p[0] |= pack_left_shift_u8(requested_motor_power, 0u, 0xffu);

    return (1);
}

int omcar_requested_motor_power_message_unpack(
    struct omcar_requested_motor_power_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t requested_motor_power;

    if (size < 1u) {
        return (-EINVAL);
    }

    requested_motor_power = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->requested_motor_power = (int8_t)requested_motor_power;

    return (0);
}

int omcar_requested_motor_power_message_init(struct omcar_requested_motor_power_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_requested_motor_power_message_t));

    return 0;
}

int8_t omcar_requested_motor_power_message_requested_motor_power_encode(double value)
{
    return (int8_t)(value);
}

double omcar_requested_motor_power_message_requested_motor_power_decode(int8_t value)
{
    return ((double)value);
}

bool omcar_requested_motor_power_message_requested_motor_power_is_in_range(int8_t value)
{
    return ((value >= -100) && (value <= 100));
}

int omcar_battery_voltage_pack(
    uint8_t *dst_p,
    const struct omcar_battery_voltage_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->battery_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->battery_voltage, 8u, 0xffu);

    return (2);
}

int omcar_battery_voltage_unpack(
    struct omcar_battery_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->battery_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->battery_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int omcar_battery_voltage_init(struct omcar_battery_voltage_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_battery_voltage_t));

    return 0;
}

uint16_t omcar_battery_voltage_battery_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double omcar_battery_voltage_battery_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool omcar_battery_voltage_battery_voltage_is_in_range(uint16_t value)
{
    return (value <= 3000u);
}

int omcar_drive_statistics_pack(
    uint8_t *dst_p,
    const struct omcar_drive_statistics_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->wheel_speed, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->odometer, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->odometer, 8u, 0xffu);

    return (3);
}

int omcar_drive_statistics_unpack(
    struct omcar_drive_statistics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->wheel_speed = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->odometer = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->odometer |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

int omcar_drive_statistics_init(struct omcar_drive_statistics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_drive_statistics_t));

    return 0;
}

uint8_t omcar_drive_statistics_wheel_speed_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_drive_statistics_wheel_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_drive_statistics_wheel_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t omcar_drive_statistics_odometer_encode(double value)
{
    return (uint16_t)(value);
}

double omcar_drive_statistics_odometer_decode(uint16_t value)
{
    return ((double)value);
}

bool omcar_drive_statistics_odometer_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int omcar_gear_select_pack(
    uint8_t *dst_p,
    const struct omcar_gear_select_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->gear_control_switch_state, 0u, 0x01u);

    return (1);
}

int omcar_gear_select_unpack(
    struct omcar_gear_select_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->gear_control_switch_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int omcar_gear_select_init(struct omcar_gear_select_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_gear_select_t));

    return 0;
}

uint8_t omcar_gear_select_gear_control_switch_state_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_gear_select_gear_control_switch_state_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_gear_select_gear_control_switch_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omcar_horn_control_pack(
    uint8_t *dst_p,
    const struct omcar_horn_control_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->horn_switch_state, 0u, 0x01u);

    return (1);
}

int omcar_horn_control_unpack(
    struct omcar_horn_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->horn_switch_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int omcar_horn_control_init(struct omcar_horn_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_horn_control_t));

    return 0;
}

uint8_t omcar_horn_control_horn_switch_state_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_horn_control_horn_switch_state_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_horn_control_horn_switch_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int omcar_light_controls_pack(
    uint8_t *dst_p,
    const struct omcar_light_controls_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->headlight_switch_state, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->left_blinker_switch_state, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->right_blinker_switch_state, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->hazard_lights_switch_state, 3u, 0x08u);

    return (1);
}

int omcar_light_controls_unpack(
    struct omcar_light_controls_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->headlight_switch_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->left_blinker_switch_state = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->right_blinker_switch_state = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->hazard_lights_switch_state = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    return (0);
}

int omcar_light_controls_init(struct omcar_light_controls_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_light_controls_t));

    return 0;
}

uint8_t omcar_light_controls_headlight_switch_state_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_light_controls_headlight_switch_state_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_light_controls_headlight_switch_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omcar_light_controls_left_blinker_switch_state_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_light_controls_left_blinker_switch_state_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_light_controls_left_blinker_switch_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omcar_light_controls_right_blinker_switch_state_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_light_controls_right_blinker_switch_state_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_light_controls_right_blinker_switch_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t omcar_light_controls_hazard_lights_switch_state_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_light_controls_hazard_lights_switch_state_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_light_controls_hazard_lights_switch_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
