/**
 * @file omcar.h
 *
 * @brief This header file was generated by cantools version 40.7.1 Wed Nov  5 00:47:46 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef OMCAR_H
#define OMCAR_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define OMCAR_REQUESTED_MOTOR_POWER_MESSAGE_FRAME_ID (0x101u)
#define OMCAR_BATTERY_VOLTAGE_FRAME_ID (0x202u)
#define OMCAR_DRIVE_STATISTICS_FRAME_ID (0x201u)
#define OMCAR_GEAR_SELECT_FRAME_ID (0x303u)
#define OMCAR_HORN_CONTROL_FRAME_ID (0x302u)
#define OMCAR_LIGHT_CONTROLS_FRAME_ID (0x301u)

/* Frame lengths in bytes. */
#define OMCAR_REQUESTED_MOTOR_POWER_MESSAGE_LENGTH (1u)
#define OMCAR_BATTERY_VOLTAGE_LENGTH (2u)
#define OMCAR_DRIVE_STATISTICS_LENGTH (3u)
#define OMCAR_GEAR_SELECT_LENGTH (1u)
#define OMCAR_HORN_CONTROL_LENGTH (1u)
#define OMCAR_LIGHT_CONTROLS_LENGTH (1u)

/* Extended or standard frame types. */
#define OMCAR_REQUESTED_MOTOR_POWER_MESSAGE_IS_EXTENDED (0)
#define OMCAR_BATTERY_VOLTAGE_IS_EXTENDED (0)
#define OMCAR_DRIVE_STATISTICS_IS_EXTENDED (0)
#define OMCAR_GEAR_SELECT_IS_EXTENDED (0)
#define OMCAR_HORN_CONTROL_IS_EXTENDED (0)
#define OMCAR_LIGHT_CONTROLS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define OMCAR_GEAR_SELECT_GEAR_CONTROL_SWITCH_STATE_FORWARD_CHOICE (0u)
#define OMCAR_GEAR_SELECT_GEAR_CONTROL_SWITCH_STATE_REVERSE_CHOICE (1u)

#define OMCAR_HORN_CONTROL_HORN_SWITCH_STATE_OFF_CHOICE (0u)
#define OMCAR_HORN_CONTROL_HORN_SWITCH_STATE_ON_CHOICE (1u)

#define OMCAR_LIGHT_CONTROLS_HEADLIGHT_SWITCH_STATE_OFF_CHOICE (0u)
#define OMCAR_LIGHT_CONTROLS_HEADLIGHT_SWITCH_STATE_ON_CHOICE (1u)

#define OMCAR_LIGHT_CONTROLS_LEFT_BLINKER_SWITCH_STATE_OFF_CHOICE (0u)
#define OMCAR_LIGHT_CONTROLS_LEFT_BLINKER_SWITCH_STATE_ON_CHOICE (1u)

#define OMCAR_LIGHT_CONTROLS_RIGHT_BLINKER_SWITCH_STATE_OFF_CHOICE (0u)
#define OMCAR_LIGHT_CONTROLS_RIGHT_BLINKER_SWITCH_STATE_ON_CHOICE (1u)

#define OMCAR_LIGHT_CONTROLS_HAZARD_LIGHTS_SWITCH_STATE_OFF_CHOICE (0u)
#define OMCAR_LIGHT_CONTROLS_HAZARD_LIGHTS_SWITCH_STATE_ON_CHOICE (1u)

/* Frame Names. */
#define OMCAR_REQUESTED_MOTOR_POWER_MESSAGE_NAME "Requested_Motor_Power_Message"
#define OMCAR_BATTERY_VOLTAGE_NAME "Battery_Voltage"
#define OMCAR_DRIVE_STATISTICS_NAME "Drive_Statistics"
#define OMCAR_GEAR_SELECT_NAME "Gear_Select"
#define OMCAR_HORN_CONTROL_NAME "Horn_Control"
#define OMCAR_LIGHT_CONTROLS_NAME "Light_Controls"

/* Signal Names. */
#define OMCAR_REQUESTED_MOTOR_POWER_MESSAGE_REQUESTED_MOTOR_POWER_NAME "Requested_Motor_Power"
#define OMCAR_BATTERY_VOLTAGE_BATTERY_VOLTAGE_NAME "Battery_Voltage"
#define OMCAR_DRIVE_STATISTICS_WHEEL_SPEED_NAME "Wheel_Speed"
#define OMCAR_DRIVE_STATISTICS_ODOMETER_NAME "Odometer"
#define OMCAR_GEAR_SELECT_GEAR_CONTROL_SWITCH_STATE_NAME "Gear_Control_Switch_State"
#define OMCAR_HORN_CONTROL_HORN_SWITCH_STATE_NAME "Horn_Switch_State"
#define OMCAR_LIGHT_CONTROLS_HEADLIGHT_SWITCH_STATE_NAME "Headlight_Switch_State"
#define OMCAR_LIGHT_CONTROLS_LEFT_BLINKER_SWITCH_STATE_NAME "Left_Blinker_Switch_State"
#define OMCAR_LIGHT_CONTROLS_RIGHT_BLINKER_SWITCH_STATE_NAME "Right_Blinker_Switch_State"
#define OMCAR_LIGHT_CONTROLS_HAZARD_LIGHTS_SWITCH_STATE_NAME "Hazard_Lights_Switch_State"

/**
 * Signals in message Requested_Motor_Power_Message.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_requested_motor_power_message_t {
    /**
     * The requested motor power
     *
     * Range: -100..100 (-100..100 %)
     * Scale: 1
     * Offset: 0
     */
    int8_t requested_motor_power;
};

/**
 * Signals in message Battery_Voltage.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_battery_voltage_t {
    /**
     * The voltage of the battery
     *
     * Range: 0..3000 (0..30 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t battery_voltage;
};

/**
 * Signals in message Drive_Statistics.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_drive_statistics_t {
    /**
     * The speed of the wheels
     *
     * Range: 0..255 (0..255 km/h)
     * Scale: 1
     * Offset: 0
     */
    uint8_t wheel_speed;

    /**
     * The odometer reading
     *
     * Range: 0..65535 (0..65535 km)
     * Scale: 1
     * Offset: 0
     */
    uint16_t odometer;
};

/**
 * Signals in message Gear_Select.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_gear_select_t {
    /**
     * Requested state of the gear
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gear_control_switch_state;
};

/**
 * Signals in message Horn_Control.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_horn_control_t {
    /**
     * Requested state of the horn
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t horn_switch_state;
};

/**
 * Signals in message Light_Controls.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_light_controls_t {
    /**
     * Requested state of headlights
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t headlight_switch_state;

    /**
     * Requested state of left blinker
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t left_blinker_switch_state;

    /**
     * Requested state of right blinker
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t right_blinker_switch_state;

    /**
     * Requested state of hazard lights
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hazard_lights_switch_state;
};

/**
 * Pack message Requested_Motor_Power_Message.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_requested_motor_power_message_pack(
    uint8_t *dst_p,
    const struct omcar_requested_motor_power_message_t *src_p,
    size_t size);

/**
 * Unpack message Requested_Motor_Power_Message.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_requested_motor_power_message_unpack(
    struct omcar_requested_motor_power_message_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Requested_Motor_Power_Message.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_requested_motor_power_message_init(struct omcar_requested_motor_power_message_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t omcar_requested_motor_power_message_requested_motor_power_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_requested_motor_power_message_requested_motor_power_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_requested_motor_power_message_requested_motor_power_is_in_range(int8_t value);

/**
 * Pack message Battery_Voltage.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_battery_voltage_pack(
    uint8_t *dst_p,
    const struct omcar_battery_voltage_t *src_p,
    size_t size);

/**
 * Unpack message Battery_Voltage.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_battery_voltage_unpack(
    struct omcar_battery_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Battery_Voltage.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_battery_voltage_init(struct omcar_battery_voltage_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omcar_battery_voltage_battery_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_battery_voltage_battery_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_battery_voltage_battery_voltage_is_in_range(uint16_t value);

/**
 * Pack message Drive_Statistics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_drive_statistics_pack(
    uint8_t *dst_p,
    const struct omcar_drive_statistics_t *src_p,
    size_t size);

/**
 * Unpack message Drive_Statistics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_drive_statistics_unpack(
    struct omcar_drive_statistics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Drive_Statistics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_drive_statistics_init(struct omcar_drive_statistics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_drive_statistics_wheel_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_drive_statistics_wheel_speed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_drive_statistics_wheel_speed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omcar_drive_statistics_odometer_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_drive_statistics_odometer_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_drive_statistics_odometer_is_in_range(uint16_t value);

/**
 * Pack message Gear_Select.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_gear_select_pack(
    uint8_t *dst_p,
    const struct omcar_gear_select_t *src_p,
    size_t size);

/**
 * Unpack message Gear_Select.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_gear_select_unpack(
    struct omcar_gear_select_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Gear_Select.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_gear_select_init(struct omcar_gear_select_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_gear_select_gear_control_switch_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_gear_select_gear_control_switch_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_gear_select_gear_control_switch_state_is_in_range(uint8_t value);

/**
 * Pack message Horn_Control.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_horn_control_pack(
    uint8_t *dst_p,
    const struct omcar_horn_control_t *src_p,
    size_t size);

/**
 * Unpack message Horn_Control.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_horn_control_unpack(
    struct omcar_horn_control_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Horn_Control.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_horn_control_init(struct omcar_horn_control_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_horn_control_horn_switch_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_horn_control_horn_switch_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_horn_control_horn_switch_state_is_in_range(uint8_t value);

/**
 * Pack message Light_Controls.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_light_controls_pack(
    uint8_t *dst_p,
    const struct omcar_light_controls_t *src_p,
    size_t size);

/**
 * Unpack message Light_Controls.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_light_controls_unpack(
    struct omcar_light_controls_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Light_Controls.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_light_controls_init(struct omcar_light_controls_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_light_controls_headlight_switch_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_light_controls_headlight_switch_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_light_controls_headlight_switch_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_light_controls_left_blinker_switch_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_light_controls_left_blinker_switch_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_light_controls_left_blinker_switch_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_light_controls_right_blinker_switch_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_light_controls_right_blinker_switch_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_light_controls_right_blinker_switch_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_light_controls_hazard_lights_switch_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_light_controls_hazard_lights_switch_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_light_controls_hazard_lights_switch_state_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
