/**
 * @file omcar.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Tue Nov  4 04:09:09 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "omcar.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int omcar_accelerator_pedal_message_pack(
    uint8_t *dst_p,
    const struct omcar_accelerator_pedal_message_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->accelerator_pedal_position, 0u, 0xffu);

    return (1);
}

int omcar_accelerator_pedal_message_unpack(
    struct omcar_accelerator_pedal_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->accelerator_pedal_position = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int omcar_accelerator_pedal_message_init(struct omcar_accelerator_pedal_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct omcar_accelerator_pedal_message_t));

    return 0;
}

uint8_t omcar_accelerator_pedal_message_accelerator_pedal_position_encode(double value)
{
    return (uint8_t)(value);
}

double omcar_accelerator_pedal_message_accelerator_pedal_position_decode(uint8_t value)
{
    return ((double)value);
}

bool omcar_accelerator_pedal_message_accelerator_pedal_position_is_in_range(uint8_t value)
{
    return (value <= 100u);
}
