/**
 * @file omcar.h
 *
 * @brief This header file was generated by cantools version 40.7.1 Tue Nov  4 04:09:09 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef OMCAR_H
#define OMCAR_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define OMCAR_ACCELERATOR_PEDAL_MESSAGE_FRAME_ID (0x100u)

/* Frame lengths in bytes. */
#define OMCAR_ACCELERATOR_PEDAL_MESSAGE_LENGTH (1u)

/* Extended or standard frame types. */
#define OMCAR_ACCELERATOR_PEDAL_MESSAGE_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define OMCAR_ACCELERATOR_PEDAL_MESSAGE_NAME "Accelerator_Pedal_Message"

/* Signal Names. */
#define OMCAR_ACCELERATOR_PEDAL_MESSAGE_ACCELERATOR_PEDAL_POSITION_NAME "Accelerator_Pedal_Position"

/**
 * Signals in message Accelerator_Pedal_Message.
 *
 * All signal values are as on the CAN bus.
 */
struct omcar_accelerator_pedal_message_t {
    /**
     * The position of the accelerator pedal
     *
     * Range: -100..100 (-100..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t accelerator_pedal_position;
};

/**
 * Pack message Accelerator_Pedal_Message.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omcar_accelerator_pedal_message_pack(
    uint8_t *dst_p,
    const struct omcar_accelerator_pedal_message_t *src_p,
    size_t size);

/**
 * Unpack message Accelerator_Pedal_Message.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omcar_accelerator_pedal_message_unpack(
    struct omcar_accelerator_pedal_message_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Accelerator_Pedal_Message.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omcar_accelerator_pedal_message_init(struct omcar_accelerator_pedal_message_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omcar_accelerator_pedal_message_accelerator_pedal_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omcar_accelerator_pedal_message_accelerator_pedal_position_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omcar_accelerator_pedal_message_accelerator_pedal_position_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
